description = 'Nainu AGI Worker Module'

dependencies {
    implementation project(':nainu-agi-common')

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
}

bootJar {
    enabled = true
    archiveBaseName = 'nainu-agi-worker'
}

jar {
    enabled = false
}
